name: in_memory_store
description: A high-performance, in-memory data store for Dart, designed for rapid access and efficient caching.
version: 1.0.1
repository: https://github.com/geridev12/in-memory-store.git
homepage: https://github.com/geridev12/in-memory-store.git
topics: [cache, memory]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.6.2

dependencies:
  collection: ^1.19.0

dev_dependencies:
  test: ^1.26.2
  very_good_analysis: ^7.0.0
